name = "SumOfExpVPMR"
uuid = "2c69873a-e0bb-44e1-90b4-d15ac3b7e936"
authors = ["Xuanzhao Gao <xz.gao@connect.ust.hk>, Jiuyang Liang and Zixuan Gao"]
version = "0.1.0"

[deps]
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
GaussQuadrature = "0.5.8"
GenericLinearAlgebra = "0.3.11"
GenericSchur = "0.5.3"
LinearAlgebra = "1"
MatrixEquations = "2.3.2"
SpecialFunctions = "2.3.1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
